### ISSUE TITLE
Unable to resolve error

### ISSUE THREAD

**Issue by brystfire08** [fjmorant/react-native-nested-listview#60]
Hello.
I installed it through npm i react-native-nested-listview

and I am getting an error:
could not resolve 'E:\\mypath\\node_modules\\react-native-listview\\dist\\src\\NestedListView as a file not as a folder'

when I looked at that folder there is no src folder inside the dist folder.

Is the installation file incomplete or am I doing something wrong?

**Comment by fjmorant** [comment]
Hi @brystfire08 ,

There has been an error in the publication of version **0.4.0**, that issue should b solved in version **0.4.3**.

Try to reinstall the package by removing the `node_modules` folder and `yarn install` again

Sorry for the inconvenience caused.

**Comment by fjmorant** [comment]
Hi @brystfire08 ,

Could you try what I mentioned above?

Thx

**Comment by brystfire08** [comment]
Tried it and it is now working thanks :)
I had to make a new project folder though coz for some reasons the react native still gets the old node modules folder folder after renaming it.
